Repository girok-web/girok-web, pull requests merged in 2024-01, with the labels that each got.

#11 버그, 리팩토링 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/refactor.md
Labels: Docs

#12 PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Docs

#10 Body 전역 스타일 제거 및 AuthLayout 컴포넌트 구현
  src/App.tsx
  src/auth/Addition.tsx
  src/auth/AuthLayout.tsx
  src/auth/SignForm.tsx
  src/auth/login/components/LoginEmail.tsx
  src/auth/login/components/LoginPassword.tsx
  src/auth/signup/components/SignupPassword.tsx
  src/auth/signup/components/SignupVerification.tsx
  src/styles/globalStyles.ts
Labels: Refactor

#17 PR 템플릿이 기본적으로 적용되도록 수정한다
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/pull_request_template.md
Labels: Bug

#15 회원가입 페이지 리팩터링
  src/App.tsx
  src/auth/signup/components/SignupEmail.tsx
  src/auth/signup/components/SignupPassword.tsx
  src/auth/signup/components/SignupVerification.tsx
  src/pages/MainPage.tsx
  src/pages/SignupPage.tsx
Labels: Refactor

#21 husky 및 lint-staged를 적용
  .husky/pre-commit
  .lintstagedrc.json
  package.json
  pnpm-lock.yaml
Labels: Feat

#23 회원가입 EndPoint 변경 반영 및 배포 완료된 Dev Server 적용
  src/auth/login/components/LoginEmail.tsx
  src/auth/login/components/LoginPassword.tsx
  src/auth/login/remotes/query.ts
  src/auth/signup/components/SignupComplete.tsx
  src/auth/signup/remotes/query.ts
  src/utils/http.ts
Labels: Refactor

#25 "회원가입"이라는 기능을 하나의 useForm 인스턴스로 관리한다
  src/auth/signup/components/SignupEmail.tsx
  src/auth/signup/components/SignupPassword.tsx
  src/auth/signup/components/SignupVerification.tsx
  src/auth/signup/remotes/query.ts
  src/pages/SignupPage.tsx
Labels: Refactor

#32 비밀번호 초기화 페이지에 퍼널, InputField, FormContext 적용
  src/App.tsx
  src/auth/reset/components/ResetComplete.tsx
  src/auth/reset/components/ResetEmail.tsx
  src/auth/reset/components/ResetPassword.tsx
  src/auth/reset/components/ResetVerification.tsx
  src/auth/reset/remotes/query.ts
  src/pages/MainPage.tsx
  src/pages/ResetPage.tsx
Labels: Refactor
